name: Packer Build

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
        mysql:
          image: mysql:latest
          ports:
            - 3306:3306

    # env:
    #   # mysql://user:password@host:port/database
    #   DATABASE_URL: "mysql://root:Abhi@123@localhost:3306/menagerie"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install dependencies
      run: |
        npm install express mysql bcrypt body-parser jest supertest dotenv portfinder nodemon sequelize sequelize-cli mysql mysql2 path fs
        npm i --save express-validator
    - name: Run unit tests
      run: |
        npm test
    - name: Health check test
      run: |
        npm test healthcheck.test.js

  packer-build:
    name: Packer Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    if: github.event.pull_request.merged == true
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Packer
      run: sudo apt-get update && sudo apt-get install -y packer
    - name: Initialize packer
      run: packer init packer
    - name: Build Packer image
      run: packer build packer/amazon-linux.pkr.hcl