name: Pull Request Unit Tests

on:
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: |
        npm install express mysql bcrypt body-parser jest supertest dotenv portfinder nodemon sequelize node-statsd sequelize-cli mysql mysql2 path fs winston aws-sdk
        npm i --save express-validator
    - name: Run unit tests
      run: |
        npm test
    - name: Health check test
      run: |
        npm test healthcheck.test.js